# Generated by Django 3.2.7 on 2022-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, db_column='user', max_length=100, null=True)),
                ('context', models.CharField(blank=True, db_column='context', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('chat_flag', models.CharField(blank=True, db_column='chat_flag', max_length=10, null=True)),
            ],
            options={
                'db_table': 'chat_info',
            },
        ),
    ]
