SECRET_KEY: 'django-insecure-n7jx3l(e*f85392$m1r=do6yr&0o+0nv9@5zn!!w)2uv2!da1*'

DATABASE:
  ENGINE: django.db.backends.sqlite3
  NAME: sqlite3
  USER: 
  PASSWORD: 
  HOST: 
  PORT: 

EMAILS:
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: 587
  EMAIL_HOST_USER: 
  EMAIL_HOST_PASSWORD: 
  
DEFAULT_GROUP: guest
DEFAULT_PASSWORD: 0000
  
ADMINS:
  1: !!python/tuple [tester1, tester1@test.com]

ALLOWED_HOSTS: [admin, client]
