# Generated by Django 3.2.7 on 2022-04-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220415_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_info',
            name='conversation_id',
            field=models.IntegerField(blank=True, db_column='conversation_id', null=True),
        ),
    ]
