# Generated by Django 3.2.7 on 2022-05-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_info_conversation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='life_quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(db_column='sentence')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'life_quotes',
                'ordering': ['created'],
            },
        ),
    ]
