# Generated by Django 3.2.7 on 2022-06-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220523_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_chat_info',
            name='voice',
            field=models.FileField(upload_to='voice_chat'),
        ),
    ]
